"""Validation utilities for Python code generated by the agent crew."""

import ast
from typing import Tuple, Optional


def validate_python_code(code: str) -> Tuple[bool, Optional[str]]:
    """Validates that a string of Python code is syntactically correct using ast.parse.

    Args:
        code: Python source code as a string.

    Returns:
        A tuple of (is_valid, error_message). If is_valid is True, error_message is None.
    """
    if not code or not isinstance(code, str) or not code.strip():
        return False, "Code is empty or whitespace only."

    try:
        ast.parse(code)
        return True, None
    except SyntaxError as e:
        error_details = f"SyntaxError on line {e.lineno}: {e.msg}"
        if e.text:
            error_details += f" (code: '{e.text.strip()}')"
        return False, error_details
    except Exception as e:
        return False, f"Unexpected error parsing code: {str(e)}"
